### ISSUE TITLE
Branding footer does not get initialized

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [grnet/djnro#21]
Hi Zenon,

While I was working on #20 yesterday, I noticed that `djnro/templates/partial/footer.html` uses BRANDING context variable, which is however not defined anywhere.  And in turn, the footer looks rather incomplete with unpopulated values.

I've had a look and all the different parts (helpdesk, social_media, service_provided_by) are defined in local_settings.py.dist - and I get most correctly populated by adding `BRANDING` to `edumanage/context_processors.py`:

```
        'BRANDING': {
             'helpdesk': settings.NRO_DOMAIN_HELPDESK_DICT,
             'social_media': settings.NRO_PROV_SOCIAL_MEDIA_CONTACT,
             'service_provided_by': settings.NRO_PROV_BY_DICT,
        },
```

There is a little bit of additional polishing required:
- Drop `DOMAIN_HELPDESK_DICT` from the context parameters (this is not used anywhere)
- Change how the social_media `icon` item is interpreted: sample definition in `local_settings.py.dist` uses paths to images, while the code in `djnro/templates/partial/footer.html` interprets this as a CSS class.

Would you like me to add this to the misc fixes PR #19 ?

Cheers,
Vlad

**Comment by zmousm** [comment]
Thanks Vladimir.

I will fix this per your guidelines, with styling like `MANAGE_LOGIN_METHODS`.

Check out #24 against master.

**Comment by vladimir-mencl-eresearch** [comment]
Thanks, this is looking great!

Cheers,
Vlad
