### ISSUE TITLE
can't load old data from 1.0 to new instance djnro 1.1.

### ISSUE THREAD

**Issue by Melkin1968** [grnet/djnro#46]
Hello,

could you please help with migartion procedure from DjNRO 1.0 to 1.1. I have two distinct instances and have tryed to make  migration from one to another as described in documentation. In the old instance I have made:
1. install and add 'fixture_magic' to INSTALLED_APPS in settings.py
2. ./manage.py dumpdata --indent=4 --natural --exclude=contenttypes --exclude=auth.Permission > /tmp/eduroam_1.0.json
3. ./manage.py reorder_fixtures --settings='settings' /tmp/eduroam_1.0.json edumanage.name_i18n edumanage.url_i18n edumanage.contact edumanage.realm edumanage.realmdata edumanage.institution edumanage.institutiondetails edumanage.institutioncontactpool edumanage.serviceloc edumanage.instserver edumanage.instrealm edumanage.instrealmmon edumanage.monlocalauthnparam edumanage.monproxybackclient > /tmp/eduroam_1.0.ordered.json
All steps have been done without any errors.

Than in new 1.1 instance:
1. (www-eduroamnew)idp:/var/www-eduroamnew/djnro# ./manage.py loaddata --settings='djnro.settings' /tmp/eduroam_1.0.ordered.json
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www-eduroamnew/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/var/www-eduroamnew/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www-eduroamnew/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www-eduroamnew/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/var/www-eduroamnew/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 60, in handle
    self.loaddata(fixture_labels)
  File "/var/www-eduroamnew/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 100, in loaddata
    self.load_label(fixture_label)
  File "/var/www-eduroamnew/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 151, in load_label
    for obj in objects:
  File "/var/www-eduroamnew/local/lib/python2.7/site-packages/django/core/serializers/json.py", line 85, in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
  File "/var/www-eduroamnew/local/lib/python2.7/site-packages/django/core/serializers/json.py", line 79, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/var/www-eduroamnew/local/lib/python2.7/site-packages/django/core/serializers/python.py", line 132, in Deserializer
    m2m_data[field.name] = [m2m_convert(pk) for pk in field_value]
django.core.serializers.base.DeserializationError: Problem installing fixture '/tmp/eduroam_1.0.ordered.json': 'int' object is not iterable

Could you please help me. 
Thank you

**Comment by zmousm** [comment]
This back-trace unfortunately doesn't say much; I might need to look at the specific fixtures data-set in order to try to reproduce any (potential) issue. It would also help if you precisely documented the specific steps you took during such a migration process, somewhat like this:

http://djnro.readthedocs.io/en/latest/installation/migrating-from-0.8-to-1.0/

**Comment by zmousm** [comment]
On a second thought, I may have an idea what could be failing:

At some point before 1.1 the relationships for one model (`InstServer`) changed to many-to-many. Django's fixtures mechanism most probably can not handle loading data from an incompatible schema version, which is something to be expected.

Therefore to migrate such data you would need to follow an upgrade process similar to the instructions for upgrading from 1.0 to 1.1, namely you would need to load data on 1.0, perform South migrations at `last-south-django1.4` and then complete the remaining steps to upgrade to 1.1, including the switch to Django migrations.

**Comment by Melkin1968** [comment]
Hi Zenon,

Thank you a lot for your help. I have made migration finally with your
help. However, I did it in way of step-by-step migration on the same DB as
was described in 'Upgrading DjNRO from 1.0 to 1.1 or later'. So, I haven't
been moved data from old DB to new.  However, I have some issues still.
Could you please help me in another questions?

1. You have described some PostgreSQL commands in 'Fix up database'
paragraph. However, I have MySQL as database and I have no idea how to
translate PostgreSQL commands in MySQL. Do I really need them? Now all
working nice without them.

2. I have setup 'Ukraine' language for I18N fields. However,  when I fill
them I have got question marks, not a cyrillic alphabet. Could you please
help me fix this issue? I set in djnro/settings.py :

LANGUAGES = ( ('uk', _('Ukraine')), ('en', _('English')),)

URL_NAME_LANGS = LANGUAGES

Thank you and best regards, Eugene Preobrazhenskyi

*Yevhenii Preobrazhenskyi*
*Technical department**, ISP URAN*
Tel: +380 (44) 454-9816 | Mobile: +380 (63) 720-1743
*eugene.melkin@gmail.com <eugene.melkin@gmail.com>* | *www.uran.ua
<http://www.uran.ua>*

2017-04-05 8:12 GMT+03:00 Zenon Mousmoulas <notifications@github.com>:

**Comment by zmousm** [comment]
> I have made migration finally with your help.

Great :)

> However, I did it in way of step-by-step migration on the same DB as was described in 'Upgrading DjNRO from 1.0 to 1.1 or later'. So, I haven't been moved data from old DB to new.

I didn't get what you mean in the last sentence but, yes, I see no reason why you should not prefer an in-place upgrade from a dump-and-reload-data migration. You would prefer the latter if you wanted to recreate the database, as noted in the docs.

> However, I have some issues still. Could you please help me in another questions?
> 1. You have described some PostgreSQL commands in 'Fix up database' paragraph. However, I have MySQL as database and I have no idea how to translate PostgreSQL commands in MySQL. Do I really need them? Now all working nice without them.

No, you don't. As noted there, the fix is PostgreSQL- and South-specific.

> 2. I have setup 'Ukraine' language for I18N fields. However, when I fill them I have got question marks, not a cyrillic alphabet. Could you please help me fix this issue?
> I set in djnro/settings.py : 
> LANGUAGES = ( ('uk', _('Ukraine')), ('en', _('English')),)
> URL_NAME_LANGS = LANGUAGES

I have no idea about this one. Please be more specific: What are you editing/filling in and where? Is your input UTF-8?

Please remember: post questions to the mailing list, use GitHub to report/investigate bugs.

Cheers
Z.

**Comment by zmousm** [comment]
Hi Yevhenii,

any news here?

**Comment by Melkin1968** [comment]
Dear Zenon,
I have resolved all my issues successfuly. It was my mistakes when I setup database with utf8 support.
Thank you for your help!
