### ISSUE TITLE
Can't change Service Location coordinates after EDB2

### ISSUE THREAD

**Issue by wakhan007** [grnet/djnro#76]
After EDB2.0, we are not able to update service location coordinates from the admin panel. There are no longitude/latitude fields or edit button to change coordinates.

**Comment by zmousm** [comment]
Ack. I am afraid I mostly neglected this part. I will try to fix this soon.

**Comment by vladimir-mencl-eresearch** [comment]
Thanks for the quick fix, @zmousm

**Comment by wakhan007** [comment]
@zmousm 
I updated some nodes on the new version and got below error from eduroam_ot

Error:
while processing your XML files following problems were found :

######## institution.xml (general/institution.xml) ########

** BEGIN error report XML file institution.xml** XML file on URL https://admintool.eduroam.pk/general/v2/institution.xml is not valid

 Error 1871: Element 'contact': This element is not expected. Expected is one of ( inst_name, address ). in /data/www/monitor/eduroam-database/v2/scripts/ on line 1 

** END error report **

**Comment by zmousm** [comment]
Hello @wakhan007, please open a new issue, as this is a different problem.
